package com.github.woodsmarshes.chat.core.network.ktor

import com.github.woodsmarshes.chat.core.network.NetworkBuildConfig
import io.ktor.http.URLProtocol

data class NetworkConfig(
    val host: String,
    val port: Int = 9051,
    val useTls: Boolean = false,
) {
    val protocol: URLProtocol
        get() = if (useTls) URLProtocol.HTTPS else URLProtocol.HTTP

    val baseUrl: String
        get() = "${protocol.name}://$host:$port"

    val wsUrl: String
        get() = "${if (useTls) "wss" else "ws"}://$host:$port/ws"

    companion object {
        fun forDevelopment(
            host: String = "127.0.0.1",
            port: Int = 9051,
        ) = NetworkConfig(
            host = host,
            port = port,
            useTls = false,
        )
    }
}

// Generated by BuildKonfig at compile time from network-config.properties.
// Falls back to development defaults if the properties file is missing.
fun loadNetworkConfig(): NetworkConfig = NetworkConfig(
    host = NetworkBuildConfig.serverHost,
    port = NetworkBuildConfig.serverPort,
    useTls = NetworkBuildConfig.serverUseTls,
)
